// client/src/components/Nav.vue
<script setup lang="ts">
    import { ref } from 'vue';
    import { RouterLink } from 'vue-router';
    import Cart from './Cart.vue';
    import LoginBadge from './LoginBadge.vue';
    import MessageList from './MessageList.vue';

    const isActive = ref(false);
    const isCartOpen = ref(false);
</script>

<template>
    <Cart :is-open="isCartOpen" />
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <div class="navbar-item">
                    <h1 class="title is-5">Web Programming</h1>
                </div>
                <a :class="{ 'is-active': isActive }" @click="isActive = !isActive" role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div id="navbarBasicExample" class="navbar-menu" :class="{ 'is-active': isActive }">
                <div class="navbar-start">
                    <RouterLink to="/" class="navbar-item">Home</RouterLink>
                    <RouterLink to="/products" class="navbar-item">Products</RouterLink>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">More</a>
                        <div class="navbar-dropdown">
                            <RouterLink to="/admin/products" class="navbar-item">Admin</RouterLink>
                            <RouterLink to="/about" class="navbar-item">About</RouterLink>
                        </div>
                    </div>
                </div>
                <div class="navbar-end">
                    <MessageList />
                    <div class="navbar-item">
                        <button class="button is-primary" @click="isCartOpen = !isCartOpen">Cart</button>
                    </div>
                    <div class="navbar-item">
                        <LoginBadge />
                    </div>
                </div>
            </div>
        </div>
    </nav>
</template>

<style>
    nav {
        padding: 0 135px 0 135px;
    }
    .router-link-active {
        border-bottom: #00AA00 5px solid;
    }
</style>

// next-app/components/Nav.tsx
import Link from "next/link"
const Cart = () => <div></div>
const LoginBadge = () => <div></div>
const MessageList = () => <div></div>

export default () => {
    return (
        <nav className="navbar is-primary" role="navigation" aria-label="main navigation">
            <Cart is-open="isCartOpen" />
            <div className="container">
                <div className="navbar-brand">
                    <div className="navbar-item">
                        <h1 className="title is-5">Web Programming</h1>
                    </div>
                    <a className="navbar-burger { 'is-active': isActive }" click="isActive = !isActive" role="button" aria-label="menu" aria-expanded="false">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>
                <div id="navbarBasicExample" className="navbar-menu { 'is-active': isActive }">
                    <div className="navbar-start">
                        <Link href="/" className="navbar-item">Home</Link>
                        <Link href="/products" className="navbar-item">Products</Link>
                        <div className="navbar-item has-dropdown is-hoverable">
                            <a className="navbar-link">More</a>
                            <div className="navbar-dropdown">
                                <Link href="/about" className="navbar-item">About</Link>
                            </div>
                        </div>
                    </div>
                    <div className="navbar-end">
                        <MessageList />
                        <div className="navbar-item">
                            <button className="button is-primary" click="isCartOpen = !isCartOpen">Cart</button>
                        </div>
                        <div className="navbar-item">
                            <LoginBadge />
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    )
}
